{
    "dataType": "CVE_RECORD",
    "dataVersion": "5.1",
    "cveMetadata": {
        "cveId": "CVE-2025-5175",
        "assignerOrgId": "1af790b2-7ee1-4545-860a-a788eba489b5",
        "state": "PUBLISHED",
        "assignerShortName": "VulDB",
        "dateReserved": "2025-05-25T13:47:05.776Z",
        "datePublished": "2025-05-26T07:31:06.272Z",
        "dateUpdated": "2025-05-26T07:31:06.272Z"
    },
    "containers": {
        "cna": {
            "providerMetadata": {
                "orgId": "1af790b2-7ee1-4545-860a-a788eba489b5",
                "shortName": "VulDB",
                "dateUpdated": "2025-05-26T07:31:06.272Z"
            },
            "title": "erdogant pypickle pypickle.py save improper authorization",
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "type": "CWE",
                            "cweId": "CWE-285",
                            "lang": "en",
                            "description": "Improper Authorization"
                        }
                    ]
                },
                {
                    "descriptions": [
                        {
                            "type": "CWE",
                            "cweId": "CWE-266",
                            "lang": "en",
                            "description": "Incorrect Privilege Assignment"
                        }
                    ]
                }
            ],
            "affected": [
                {
                    "vendor": "erdogant",
                    "product": "pypickle",
                    "versions": [
                        {
                            "version": "1.1.0",
                            "status": "affected"
                        },
                        {
                            "version": "1.1.1",
                            "status": "affected"
                        },
                        {
                            "version": "1.1.2",
                            "status": "affected"
                        },
                        {
                            "version": "1.1.3",
                            "status": "affected"
                        },
                        {
                            "version": "1.1.4",
                            "status": "affected"
                        },
                        {
                            "version": "1.1.5",
                            "status": "affected"
                        }
                    ]
                }
            ],
            "descriptions": [
                {
                    "lang": "en",
                    "value": "A vulnerability was found in erdogant pypickle up to 1.1.5. It has been classified as critical. This affects the function Save of the file pypickle/pypickle.py. The manipulation leads to improper authorization. Attacking locally is a requirement. The exploit has been disclosed to the public and may be used. Upgrading to version 2.0.0 is able to address this issue. The patch is named 14b4cae704a0bb4eb6723e238f25382d847a1917. It is recommended to upgrade the affected component."
                },
                {
                    "lang": "de",
                    "value": "Es wurde eine Schwachstelle in erdogant pypickle bis 1.1.5 ausgemacht. Sie wurde als kritisch eingestuft. Dabei betrifft es die Funktion Save der Datei pypickle/pypickle.py. Durch Manipulieren mit unbekannten Daten kann eine improper authorization-Schwachstelle ausgenutzt werden. Der Angriff muss lokal erfolgen. Der Exploit steht zur öffentlichen Verfügung. Ein Aktualisieren auf die Version 2.0.0 vermag dieses Problem zu lösen. Der Patch wird als 14b4cae704a0bb4eb6723e238f25382d847a1917 bezeichnet. Als bestmögliche Massnahme wird das Einspielen eines Upgrades empfohlen."
                }
            ],
            "metrics": [
                {
                    "cvssV4_0": {
                        "version": "4.0",
                        "baseScore": 4.8,
                        "vectorString": "CVSS:4.0/AV:L/AC:L/AT:N/PR:L/UI:N/VC:L/VI:L/VA:L/SC:N/SI:N/SA:N",
                        "baseSeverity": "MEDIUM"
                    }
                },
                {
                    "cvssV3_1": {
                        "version": "3.1",
                        "baseScore": 5.3,
                        "vectorString": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:L/I:L/A:L",
                        "baseSeverity": "MEDIUM"
                    }
                },
                {
                    "cvssV3_0": {
                        "version": "3.0",
                        "baseScore": 5.3,
                        "vectorString": "CVSS:3.0/AV:L/AC:L/PR:L/UI:N/S:U/C:L/I:L/A:L",
                        "baseSeverity": "MEDIUM"
                    }
                },
                {
                    "cvssV2_0": {
                        "version": "2.0",
                        "baseScore": 4.3,
                        "vectorString": "AV:L/AC:L/Au:S/C:P/I:P/A:P"
                    }
                }
            ],
            "timeline": [
                {
                    "time": "2025-05-25T00:00:00.000Z",
                    "lang": "en",
                    "value": "Advisory disclosed"
                },
                {
                    "time": "2025-05-25T02:00:00.000Z",
                    "lang": "en",
                    "value": "VulDB entry created"
                },
                {
                    "time": "2025-05-25T15:52:20.000Z",
                    "lang": "en",
                    "value": "VulDB entry last update"
                }
            ],
            "credits": [
                {
                    "lang": "en",
                    "value": "Prince Raj (VulDB User)",
                    "type": "reporter"
                }
            ],
            "references": [
                {
                    "url": "https://vuldb.com/?id.310263",
                    "name": "VDB-310263 | erdogant pypickle pypickle.py save improper authorization",
                    "tags": [
                        "vdb-entry",
                        "technical-description"
                    ]
                },
                {
                    "url": "https://vuldb.com/?ctiid.310263",
                    "name": "VDB-310263 | CTI Indicators (IOB, IOC, TTP, IOA)",
                    "tags": [
                        "signature",
                        "permissions-required"
                    ]
                },
                {
                    "url": "https://vuldb.com/?submit.579824",
                    "name": "Submit #579824 | erdogant pypickle 1.1.5 File Overwrite Vulnerability",
                    "tags": [
                        "third-party-advisory"
                    ]
                },
                {
                    "url": "https://github.com/erdogant/pypickle/issues/3",
                    "tags": [
                        "issue-tracking"
                    ]
                },
                {
                    "url": "https://github.com/erdogant/pypickle/issues/3#issuecomment-2888589652",
                    "tags": [
                        "issue-tracking"
                    ]
                },
                {
                    "url": "https://github.com/erdogant/pypickle/issues/3#issue-3070689116",
                    "tags": [
                        "exploit",
                        "issue-tracking"
                    ]
                },
                {
                    "url": "https://github.com/erdogant/pypickle/commit/14b4cae704a0bb4eb6723e238f25382d847a1917",
                    "tags": [
                        "patch"
                    ]
                },
                {
                    "url": "https://github.com/erdogant/pypickle/releases/tag/2.0.0",
                    "tags": [
                        "patch"
                    ]
                }
            ]
        }
    }
}